name: tdmpc

channels:  
  - pytorch
  - conda-forge
  - nvidia
  - defaults  
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - torchtext
  - cudatoolkit=10.2

  - pip
  - pip:
      - termcolor
      - omegaconf
      - gym==0.21.0
      - dm-control==0.0.403778684
      - pandas
      - wandb
      - moviepy
      - imageio
