name: tdmpc
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pytorch=1.9.1
  - torchvision=0.10.1
  - torchaudio=0.9.1
  - torchtext=0.10.1
  - cudatoolkit=11.3
  - pip
  - pip:
      - termcolor
      - omegaconf
      - gym==0.21.0
      - dm-control==0.0.403778684
      - pandas
      - wandb
      - moviepy
      - imageio
      - mujoco-py
  
